development:
  Store:
    deploy: false
  Submarket:
    deploy: false
  Order:
    deploy: false
  Forum:
    deploy: false
  aliasable:
    deploy: false
  owned:
    deploy: false
  forumable:
    deploy: false
  audible:
    deploy: false
  infosphered:
    deploy: false
  permissioned:
    deploy: false
  meta:
    deploy: false
  AliasReg:
    deploy: true
  Keystore:
    deploy: true
  OrderBook:
    deploy: true
  OpenStore:
    onDeploy:
      - OpenStore = web3.eth.contract(contracts.OpenStore.abi).at(contracts.OpenStore.address);
      - OpenStore.set('CMC:TETH:USD', new BigNumber('830075000000'));
      - OpenStore.set('CMC:TETH:EUR', new BigNumber('782024448475'));
      - OpenStore.set('CMC:TETH:CNY', new BigNumber('5311462328050'));
      - OpenStore.set('CMC:TETH:CAD', new BigNumber('1107984940080'));
      - OpenStore.set('CMC:TETH:RUB', new BigNumber('55780151819800'));
      - OpenStore.set('CMC:TETH:BTC', new BigNumber('2306400000'));
      - web3.eth.sendTransaction({to:'0x1049a6c61c46a7c1e12d919189701bf26a1a2011',value:web3.toWei(10,'ether')})
production:
  Store:
    deploy: false
  Submarket:
    deploy: false
  Order:
    deploy: false
  Forum:
    deploy: false
  aliasable:
    deploy: false
  owned:
    deploy: false
  forumable:
    deploy: false
  audible:
    deploy: false
  infosphered:
    deploy: false
  permissioned:
    deploy: false
  meta:
    deploy: false 
  AliasReg:
    deploy: true
  Keystore:
    deploy: true
  OrderBook:
    deploy: true
  OpenStore:
    deploy: false
